testAll: test1 test2 test3 test4 test5 test6 test7 test8

test1: 
	@echo -- running with test-input-1 --
	python TSP.py test-input-1.txt
	@echo -- Running test --
	python tsp-verifier.py test-input-1.txt test-input-1.txt.tour

test2:
	@echo -- running with test-input-2 --
	python TSP.py test-input-2.txt
	@echo -- Running test --
	python tsp-verifier.py test-input-2.txt test-input-2.txt.tour

test3:
	@echo -- running with test-input-3 --
	python TSP.py test-input-3.txt
	@echo -- Running test --
	python tsp-verifier.py test-input-3.txt test-input-3.txt.tour

test4:
	@echo -- running with test-input-4 --
	python TSP.py test-input-4.txt
	@echo -- Running test --
	python tsp-verifier.py test-input-4.txt test-input-4.txt.tour

test5:
	@echo -- running with test-input-5 --
	python TSP.py test-input-5.txt
	@echo -- Running test --
	python tsp-verifier.py test-input-5.txt test-input-5.txt.tour

test6:
	@echo -- running with test-input-6 --
	python TSP.py test-input-6.txt
	@echo -- Running test --
	python tsp-verifier.py test-input-6.txt test-input-6.txt.tour

test7:
	@echo -- running with test-input-7 --
	python TSP.py test-input-7.txt
	@echo -- Running test --
	python tsp-verifier.py test-input-7.txt test-input-7.txt.tour

test8:
	@echo -- running with test-input-8 --
	python TSP.py test-input-8-2.txt
	@echo -- Running test --
	python tsp-verifier.py test-input-8-2.txt test-input-8-2.txt.tour